C:\Projects\AADS\Support\AudioMgr\Mss32.lib
C:\Projects\AADS\Support\AudioMgr\Debug\audiomgr.lib
C:\Projects\AADS\Support\AudioMgr\Linux-Debug\audiomgr.lib
C:\Projects\AADS\Support\AudioMgr\Release\audiomgr.lib
C:\Projects\AADS\Support\BotEditor\Debug\BotEditor.lib
C:\Projects\AADS\Support\BotEditor\Release\BotEditor.lib
C:\Projects\AADS\Support\Building\Debug\BuildingObject.lib
C:\Projects\AADS\Support\Building\Linux-Debug\BuildingObject.lib
C:\Projects\AADS\Support\Building\Release\BuildingObject.lib
C:\Projects\AADS\Support\CardMgr\Debug\cardmgr.lib
C:\Projects\AADS\Support\CardMgr\Release\cardmgr.lib
C:\Projects\AADS\Support\CleanText\Debug\CleanText.lib
C:\Projects\AADS\Support\CleanText\Linux-Debug\CleanText.lib
C:\Projects\AADS\Support\CleanText\Release\CleanText.lib
C:\Projects\AADS\Support\GameMgr\Debug\GameMgr.lib
C:\Projects\AADS\Support\GameMgr\Linux-Debug\GameMgr.lib
C:\Projects\AADS\Support\GameMgr\Release\GameMgr.lib
C:\Projects\AADS\Support\HUD\Debug\HUD.lib
C:\Projects\AADS\Support\HUD\Linux-Debug\HUD.lib
C:\Projects\AADS\Support\HUD\Release\HUD.lib
C:\Projects\AADS\Support\LabelSets\Linux-Debug\LabelSets.lib
C:\Projects\AADS\Support\LabelSets\PC-Debug\LabelSets.lib
C:\Projects\AADS\Support\LabelSets\PC-Release\LabelSets.lib
C:\Projects\AADS\Support\MasterServer\Debug\MasterServer.lib
C:\Projects\AADS\Support\MasterServer\Linux-Debug\MasterServer.lib
C:\Projects\AADS\Support\MasterServer\Release\MasterServer.lib
C:\Projects\AADS\Support\MoviePlayer\Debug\MoviePlayer.lib
C:\Projects\AADS\Support\MoviePlayer\Release\MoviePlayer.lib
C:\Projects\AADS\Support\netlib\Linux-Debug\NetLib.lib
C:\Projects\AADS\Support\netlib\PC\WS2_32.LIB
C:\Projects\AADS\Support\netlib\PC-Debug\NetLib.lib
C:\Projects\AADS\Support\netlib\PC-Release\NetLib.lib
C:\Projects\AADS\Support\ObjectMgr\Debug\ObjectMgr.lib
C:\Projects\AADS\Support\ObjectMgr\Linux-Debug\ObjectMgr.lib
C:\Projects\AADS\Support\ObjectMgr\Release\ObjectMgr.lib
C:\Projects\AADS\Support\Objects\Bot\Debug\BotObject.lib
C:\Projects\AADS\Support\Objects\Bot\Linux-Debug\BotObject.lib
C:\Projects\AADS\Support\Objects\Bot\Release\BotObject.lib
C:\Projects\AADS\Support\Objects\Pickups\Debug\Pickups.lib
C:\Projects\AADS\Support\Objects\Pickups\Linux-Debug\Pickups.lib
C:\Projects\AADS\Support\Objects\Pickups\Release\Pickups.lib
C:\Projects\AADS\Support\Objects\Player\Linux-Debug\PlayerObject.lib
C:\Projects\AADS\Support\Objects\Player\PC-Debug\PlayerObject.lib
C:\Projects\AADS\Support\Objects\Player\PC-Release\PlayerObject.lib
C:\Projects\AADS\Support\Objects\Projectiles\Debug\Projectiles.lib
C:\Projects\AADS\Support\Objects\Projectiles\Linux-Debug\Projectiles.lib
C:\Projects\AADS\Support\Objects\Projectiles\Release\Projectiles.lib
C:\Projects\AADS\Support\Objects\Terrain\Debug\Terrain.lib
C:\Projects\AADS\Support\Objects\Terrain\Linux-Debug\Terrain.lib
C:\Projects\AADS\Support\Objects\Terrain\Release\Terrain.lib
C:\Projects\AADS\Support\Objects\Vehicles\Debug\Vehicle.lib
C:\Projects\AADS\Support\Objects\Vehicles\Linux-Debug\Vehicle.lib
C:\Projects\AADS\Support\Objects\Vehicles\Release\Vehicle.lib
C:\Projects\AADS\Support\Particles\Debug\Particles.lib
C:\Projects\AADS\Support\Particles\Linux-Debug\Particles.lib
C:\Projects\AADS\Support\Particles\Release\Particles.lib
C:\Projects\AADS\Support\Poly\Debug\poly.lib
C:\Projects\AADS\Support\Poly\Release\poly.lib
C:\Projects\AADS\Support\Shape\Linux-Debug\Shape.lib
C:\Projects\AADS\Support\Shape\PC-Debug\Shape.lib
C:\Projects\AADS\Support\Shape\PC-Release\Shape.lib
C:\Projects\AADS\Support\Sky\PC-Debug\Sky.lib
C:\Projects\AADS\Support\Sky\PC-Release\Sky.lib
C:\Projects\AADS\Support\StringMgr\Debug\StringMgr.lib
C:\Projects\AADS\Support\StringMgr\Linux-Debug\StringMgr.lib
C:\Projects\AADS\Support\StringMgr\Release\StringMgr.lib
C:\Projects\AADS\Support\TelnetConsole\Debug\TelnetConsole.lib
C:\Projects\AADS\Support\TelnetConsole\Linux-Debug\TelnetConsole.lib
C:\Projects\AADS\Support\TelnetConsole\Release\TelnetConsole.lib
C:\Projects\AADS\Support\Tokenizer\Linux-Debug\Tokenizer.lib
C:\Projects\AADS\Support\Tokenizer\PC-Debug\Tokenizer.lib
C:\Projects\AADS\Support\Tokenizer\PC-Release\Tokenizer.lib
C:\Projects\AADS\Support\UI\Debug\UI.lib
C:\Projects\AADS\Support\UI\Linux-Debug\UI.lib
C:\Projects\AADS\Support\UI\Release\UI.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\amstrmid.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\d3d8.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\d3dx.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\d3dx8.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\d3dx8d.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\d3dx8dt.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\d3dxd.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\d3dxof.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\ddraw.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dinput.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dinput8.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dmoguids.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dplayx.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dpnaddr.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dpnet.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dpnlobby.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dpvoice.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\DSETUP.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dsound.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dxerr8.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dxguid.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\dxtrans.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\ksproxy.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\ksuser.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\msdmo.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\qedit.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\quartz.lib
C:\Projects\AADS\xCore\3rdParty\DirectX8\strmiids.lib
C:\Projects\AADS\xCore\3rdParty\Miles6\lib\win\Mss32.lib
C:\Projects\AADS\xCore\3rdParty\Miles6\src\M3d\Rsx\Rsxcore.lib
C:\Projects\AADS\xCore\Auxiliary\Bitmap\Debug\aux_Bitmap.lib
C:\Projects\AADS\xCore\Auxiliary\Bitmap\Linux-Debug\aux_Bitmap.lib
C:\Projects\AADS\xCore\Auxiliary\Bitmap\Release\aux_Bitmap.lib
C:\Projects\AADS\xCore\Entropy\Debug\Entropy.lib
C:\Projects\AADS\xCore\Entropy\Linux-Debug\Entropy.lib
C:\Projects\AADS\xCore\Entropy\Release\Entropy.lib
C:\Projects\AADS\xCore\Projects\SoundPkg\LIBRARY\ENCVAG.LIB
C:\Projects\AADS\xCore\x_files\Debug\x_files.lib
C:\Projects\AADS\xCore\x_files\Linux-Debug\x_files.lib
C:\Projects\AADS\xCore\x_files\Release\x_files.lib
